apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
  annotations: 
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      name: http-nginx
    - port: 443
      name: https-nginx
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Never
