apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations: 
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:
    app: ftps
  ports:
    - port: 21
      name: ftps-port
    - port: 30001
      name: ftps-range
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 30001
